CREATE Table users (
  user_id integer AUTO_INCREMENT,
  name varchar(100) NOT NULL,
  email varchar(100) NOT NULL,
  password varchar(100) NOT NULL,
  created_at timestamp,
  PRIMARY KEY (user_id)
);

CREATE Table tokens (
  id_token int AUTO_INCREMENT NOT NULL,
  user_id int(11) NOT NULL,
  token text NOT NULL,
  expires_at timestamp NOT NULL,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY (id_token),
  FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE symptoms (
    id INT AUTO_INCREMENT PRIMARY KEY,
    symptom VARCHAR(255) NOT NULL
);

INSERT INTO symptoms (symptom) VALUES
('abdominal pain'),
('abnormal menstruation'),
('acidity'),
('acute liver failure'),
('altered sensorium'),
('anxiety'),
('back pain'),
('belly pain'),
('blackheads'),
('bladder discomfort'),
('blister'),
('blood in sputum'),
('bloody stool'),
('blurred and distorted vision'),
('breathlessness'),
('brittle nails'),
('bruising'),
('burning micturition'),
('chest pain'),
('chills'),
('Yellowish skin'),
('cold hands and feets'),
('coma'),
('congestion'),
('constipation'),
('continuous feel of urine'),
('continuous sneezing'),
('cough'),
('cramps'),
('dark urine'),
('dehydration'),
('depression'),
('diarrhoea'),
('dischromic patches'),
('distention of abdomen'),
('dizziness'),
('drying and tingling lips'),
('enlarged thyroid'),
('excessive hunger'),
('extra marital contacts'),
('family history'),
('fast heart rate'),
('fatigue'),
('fluid overload'),
('foul smell of urine'),
('headache'),
('high fever'),
('hip joint pain'),
('history of alcohol consumption'),
('increased appetite'),
('indigestion'),
('inflammatory nails'),
('internal itching'),
('irregular sugar level'),
('irritability'),
('irritation in anus'),
('itching'),
('joint pain'),
('knee pain'),
('lack of concentration'),
('lethargy'),
('loss of appetite'),
('loss of balance'),
('loss of smell'),
('malaise'),
('mild fever'),
('mood swings'),
('movement stiffness'),
('mucoid sputum'),
('muscle pain'),
('muscle wasting'),
('muscle weakness'),
('nausea'),
('neck pain'),
('nodal skin eruptions'),
('obesity'),
('pain behind the eyes'),
('pain during bowel movements'),
('pain in anal region'),
('painful walking'),
('palpitations'),
('passage of gases'),
('patches in throat'),
('phlegm'),
('polyuria'),
('prominent veins on calf'),
('puffy face and eyes'),
('pus filled pimples'),
('receiving blood transfusion'),
('receiving unsterile injections'),
('red sore around nose'),
('red spots over body'),
('redness of eyes'),
('restlessness'),
('runny nose'),
('rusty sputum'),
('scurring'),
('shivering'),
('silver-like dusting'),
('sinus pressure'),
('skin peeling'),
('skin rash'),
('slurred speech'),
('small dents in nails'),
('spinning movements'),
('spotting urination'),
('stiff neck'),
('stomach bleeding'),
('stomach pain'),
('sunken eyes'),
('sweating'),
('swelled lymph nodes'),
('swelling joints'),
('swelling of stomach'),
('swollen blood vessels'),
('swollen extremities'),
('swollen legs'),
('throat irritation'),
('toxic look (typhos)'),
('ulcers on tongue'),
('unsteadiness'),
('visual disturbances'),
('vomiting'),
('watering from eyes'),
('weakness in limbs'),
('weakness of one body side'),
('weight gain'),
('weight loss'),
('yellow crust ooze'),
('yellow urine'),
('yellowing of eyes'),
('yellowish skin');


CREATE Table histories (
  history_id int AUTO_INCREMENT NOT NULL,
  user_id int(11) NOT NULL,
  symptoms VARCHAR(255) NOT NULL,
  disease VARCHAR(100) NOT NULL,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY (history_id),
  FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE diseases (
    disease VARCHAR(100),
    description TEXT,
    causes TEXT,
    treatment TEXT
);

INSERT INTO diseases (disease, description, causes, treatment) VALUES
('(vertigo) Paroymsal  Positional Vertigo', 'Paroxysmal Positional Vertigo (PPV) is a condition characterized by brief episodes of mild to intense dizziness, often triggered by changes in the position of the head. It occurs due to a problem in the inner ear, specifically when tiny calcium particles clump up in canals of the inner ear.', 'Dislodged calcium carbonate crystals in the inner ear.', 'Canalith repositioning maneuvers (e.g., Epley maneuver), medications, and in some cases, surgery.'),
('AIDS', 'AIDS (Acquired Immunodeficiency Syndrome) is the most severe phase of HIV infection. It occurs when the immune system is severely damaged and unable to fight off infections and diseases, leading to life-threatening conditions.', 'Human Immunodeficiency Virus (HIV) infection.', 'Antiretroviral therapy (ART), prevention and treatment of opportunistic infections, and supportive care.'),
('Acne', 'Acne is a skin condition that occurs when hair follicles become plugged with oil and dead skin cells. It often causes whiteheads, blackheads, or pimples, and usually appears on the face, forehead, chest, upper back, and shoulders.', 'Excess oil production, hair follicles clogged by oil and dead skin cells, bacteria, and inflammation.', 'Topical treatments, oral medications, therapies, and lifestyle changes.'),
('Alcoholic hepatitis', 'Alcoholic hepatitis is inflammation of the liver caused by drinking alcohol. Symptoms include jaundice, abdominal pain, and fever.', 'Excessive alcohol consumption.', 'Abstinence from alcohol, medications, nutritional therapy, and, in severe cases, liver transplant.'),
('Allergy', 'An allergy is an immune system response to a foreign substance that''s not typically harmful to your body. These foreign substances are called allergens and can include certain foods, pollen, or pet dander.', 'Immune system response to allergens.', 'Avoiding allergens, medications, immunotherapy, and emergency epinephrine.'),
('Arthritis', 'Arthritis is the swelling and tenderness of one or more of your joints. The main symptoms of arthritis are joint pain and stiffness, which typically worsen with age. The most common types of arthritis are osteoarthritis and rheumatoid arthritis.', 'Joint inflammation due to aging, autoimmune disorders, injuries, and infections.', 'Medications, physical therapy, lifestyle changes, and sometimes surgery.'),
('Bronchial Asthma', 'Bronchial asthma is a condition in which your airways narrow and swell and may produce extra mucus. This can make breathing difficult and trigger coughing, wheezing, and shortness of breath.', 'Genetic factors, environmental triggers, respiratory infections, and allergens.', 'Inhalers, medications, avoiding triggers, and lifestyle changes.'),
('Cervical spondylosis', 'Cervical spondylosis is age-related wear and tear affecting the spinal disks in your neck. Symptoms include neck pain, stiffness, and headaches.', 'Degenerative changes in the cervical spine due to aging.', 'Medications, physical therapy, and sometimes surgery.'),
('Chicken pox', 'Chickenpox is a highly contagious viral infection causing an itchy, blister-like rash on the skin. It is caused by the varicella-zoster virus.', 'Varicella-zoster virus infection.', 'Antihistamines for itching, antiviral drugs, and supportive care.'),
('Chronic Cholestasis', 'Chronic cholestasis is a condition where bile flow from the liver is reduced or blocked. Symptoms include jaundice, itching, and fatigue.', 'Liver diseases, bile duct blockages, and certain medications.', 'Medications, surgical procedures, and managing underlying conditions.'),
('Common Cold', 'The common cold is a viral infection of your nose and throat (upper respiratory tract). It''s usually harmless, although it might not feel that way. Many types of viruses can cause a common cold.', 'Rhinoviruses and other viruses.', 'Rest, fluids, over-the-counter cold remedies, and supportive care.'),
('Dengue', 'Dengue is a mosquito-borne viral infection causing flu-like illness and, occasionally, developing into severe dengue. Symptoms include high fever, severe headache, pain behind the eyes, joint and muscle pain, rash, and mild bleeding.', 'Dengue virus transmitted by Aedes mosquitoes.', 'Supportive care, hydration, and pain relief. No specific antiviral treatment.'),
('Diabetes', 'Diabetes is a chronic disease that occurs either when the pancreas does not produce enough insulin or when the body cannot effectively use the insulin it produces. This leads to increased blood glucose levels.', 'Type 1 diabetes: autoimmune destruction of insulin-producing cells; Type 2 diabetes: insulin resistance and relative insulin deficiency.', 'Insulin therapy, oral medications, lifestyle changes, and regular monitoring.'),
('Dimorphic hemmorhoids(piles)', 'Hemorrhoids, also known as piles, are swollen veins in your anus and lower rectum, similar to varicose veins. They can develop inside the rectum (internal hemorrhoids) or under the skin around the anus (external hemorrhoids).', 'Straining during bowel movements, chronic constipation or diarrhea, obesity, and pregnancy.', 'Topical treatments, dietary changes, procedures to remove or reduce hemorrhoids.'),
('Drug Reaction', 'A drug reaction is an unintended and harmful reaction to a medication. These reactions can range from mild side effects to severe allergic reactions.', 'Allergic reactions, side effects, drug interactions, and overdose.', 'Discontinuation of the drug, medications to treat symptoms, and emergency care for severe reactions.'),
('Fungal infection', 'Fungal infections are caused by fungi and can affect various parts of the body, including the skin, nails, and respiratory system. Common fungal infections include athlete''s foot, ringworm, and thrush.', 'Fungal pathogens such as Candida, Dermatophytes, and Aspergillus.', 'Antifungal medications (topical or oral) and maintaining good hygiene.'),
('GERD', 'Gastroesophageal reflux disease (GERD) is a chronic condition where stomach acid frequently flows back into the tube connecting your mouth and stomach (esophagus). This acid reflux can irritate the lining of your esophagus.', 'Frequent acid reflux due to a weak or malfunctioning lower esophageal sphincter.', 'Lifestyle changes, medications (antacids, H2 blockers, proton pump inhibitors), and in severe cases, surgery.'),
('Gastroenteritis', 'Gastroenteritis is an inflammation of the stomach and intestines, typically resulting from bacterial toxins or viral infection and causing vomiting and diarrhea.', 'Viruses (e.g., norovirus), bacteria (e.g., E. coli), parasites, and contaminated food or water.', 'Hydration, rest, and, in some cases, antibiotics or antiviral medications.'),
('Heart Attack', 'A heart attack, or myocardial infarction, occurs when blood flow to a part of the heart is blocked for a long enough time that part of the heart muscle is damaged or dies.', 'Blockage of coronary arteries due to plaques (atherosclerosis) or blood clots.', 'Emergency medical care, medications, surgical procedures (angioplasty, stenting), and lifestyle changes.'),
('Hepatitis B', 'Hepatitis B is a serious liver infection caused by the hepatitis B virus (HBV). It can become chronic, leading to liver failure, liver cancer, or cirrhosis.', 'Hepatitis B virus (HBV) infection, often through blood, semen, or other body fluids.', 'Antiviral medications, regular monitoring, and in severe cases, liver transplant. Vaccination for prevention.'),
('Hepatitis C', 'Hepatitis C is a liver infection caused by the hepatitis C virus (HCV). It often leads to chronic liver disease, liver cirrhosis, and liver cancer if left untreated.', 'Hepatitis C virus (HCV) infection, primarily through contact with infected blood.', 'Antiviral medications, regular monitoring, and lifestyle changes to manage liver health.'),
('Hepatitis D', 'Hepatitis D is a serious liver disease caused by the hepatitis D virus (HDV). It occurs only in those infected with hepatitis B virus, as HDV requires hepatitis B virus for its replication.', 'Hepatitis D virus (HDV) infection, which occurs in conjunction with hepatitis B infection.', 'Interferon alpha treatment, monitoring, and managing hepatitis B infection.'),
('Hepatitis E', 'Hepatitis E is a liver disease caused by the hepatitis E virus (HEV). It usually results in an acute infection and is often self-limiting, but it can be severe in pregnant women.', 'Hepatitis E virus (HEV) infection, typically through contaminated water.', 'Supportive care, maintaining hydration, and in severe cases, hospitalization.'),
('Hypertension', 'Hypertension, or high blood pressure, is a condition in which the force of the blood against the artery walls is too high. It often has no symptoms but can lead to severe health complications such as heart disease and stroke.', 'Genetics, unhealthy lifestyle (poor diet, lack of exercise), obesity, stress, and underlying health conditions.', 'Lifestyle changes (diet, exercise), medications, and regular monitoring.'),
('Hyperthyroidism', 'Hyperthyroidism is a condition where the thyroid gland is overactive and produces excessive amounts of thyroid hormones. Symptoms include weight loss, rapid heartbeat, sweating, and nervousness.', 'Overactive thyroid gland due to autoimmune disorders (e.g., Graves'' disease), thyroid nodules, and inflammation.', 'Medications, radioactive iodine therapy, and sometimes surgery.'),
('Hypoglycemia', 'Hypoglycemia is a condition characterized by abnormally low blood glucose (blood sugar) levels. Symptoms include shakiness, sweating, confusion, and in severe cases, loss of consciousness.', 'Excessive insulin, certain medications, prolonged fasting, excessive alcohol consumption, and certain medical conditions.', 'Consuming fast-acting carbohydrates (e.g., glucose tablets, fruit juice), adjusting medications, and addressing underlying causes.'),
('Hypothyroidism', 'Hypothyroidism is a condition where the thyroid gland is underactive and doesn''t produce enough thyroid hormones. Symptoms include fatigue, weight gain, and depression.', 'Underactive thyroid gland due to autoimmune disorders (e.g., Hashimoto''s thyroiditis), certain medications, and iodine deficiency.', 'Thyroid hormone replacement therapy and regular monitoring.'),
('Impetigo', 'Impetigo is a highly contagious skin infection that mainly affects infants and young children. It usually appears as red sores on the face, especially around a child''s nose and mouth.', 'Bacterial infection (Staphylococcus aureus or Streptococcus pyogenes).', 'Antibiotic ointments or oral antibiotics, maintaining good hygiene, and preventing the spread of infection.'),
('Jaundice', 'Jaundice is a condition in which the skin, whites of the eyes, and mucous membranes turn yellow due to a high level of bilirubin, a yellow-orange bile pigment. It is often a symptom of an underlying condition.', 'Liver diseases, bile duct obstruction, hemolysis, and certain medications.', 'Treatment of the underlying cause, supportive care, and sometimes phototherapy (for newborns).'),
('Malaria', 'Malaria is a life-threatening disease caused by parasites that are transmitted to people through the bites of infected female Anopheles mosquitoes. Symptoms include fever, chills, and flu-like illness.', 'Plasmodium parasites transmitted by Anopheles mosquitoes.', 'Antimalarial medications, prevention strategies (mosquito nets, repellents), and supportive care.'),
('Migraine', 'A migraine is a headache of varying intensity, often accompanied by nausea and sensitivity to light and sound. It can be preceded by sensory warning symptoms (auras).', 'Genetic and environmental factors, brain chemistry, and hormonal changes.', 'Medications to relieve symptoms, preventive treatments, and lifestyle changes.'),
('Osteoarthristis', 'Osteoarthritis is the most common form of arthritis, affecting millions of people worldwide. It occurs when the protective cartilage that cushions the ends of the bones wears down over time.', 'Wear and tear of joint cartilage due to aging, injury, or repetitive use.', 'Medications, physical therapy, lifestyle changes, and sometimes surgery.'),
('Paralysis (brain hemorrhage)', 'Paralysis due to a brain hemorrhage occurs when a ruptured blood vessel causes bleeding inside the brain, leading to brain damage and loss of muscle function.', 'High blood pressure, trauma, aneurysms, and blood vessel abnormalities.', 'Emergency medical care, surgery, rehabilitation, and supportive care.'),
('Peptic Ulcer Disease', 'Peptic ulcer disease involves open sores that develop on the inside lining of your stomach and the upper portion of your small intestine. The most common symptom of a peptic ulcer is stomach pain.', 'Infection with Helicobacter pylori, long-term use of NSAIDs, and other factors.', 'Medications to reduce stomach acid, antibiotics, lifestyle changes, and sometimes surgery.'),
('Pneumonia', 'Pneumonia is an infection that inflames the air sacs in one or both lungs, which may fill with fluid or pus. Symptoms include cough, fever, chills, and difficulty breathing.', 'Bacteria, viruses, fungi, and aspiration of food, liquids, or vomit.', 'Antibiotics or antivirals, rest, fluids, and supportive care.'),
('Psoriasis', 'Psoriasis is a chronic skin condition that causes skin cells to multiply up to 10 times faster than normal, leading to bumpy red patches covered with white scales.', 'Genetic factors, immune system dysfunction.', 'Topical treatments, phototherapy, systemic medications.'),
('Tuberculosis', 'Tuberculosis (TB) is a potentially serious infectious disease that mainly affects the lungs. It is caused by the bacterium Mycobacterium tuberculosis.', 'Mycobacterium tuberculosis infection.', 'Long-term antibiotic treatment, usually involving multiple drugs.'),
('Typhoid', 'Typhoid fever is a bacterial infection that can spread throughout the body, affecting many organs. It is caused by Salmonella Typhi.', 'Salmonella Typhi bacteria, typically through contaminated food or water.', 'Antibiotics, hydration, and supportive care.'),
('Urinary tract infection', 'A urinary tract infection (UTI) is an infection in any part of your urinary system — your kidneys, ureters, bladder, and urethra.', 'Bacteria, particularly Escherichia coli (E. coli), entering the urinary tract.', 'Antibiotics, increased fluid intake, and good hygiene practices.'),
('Varicose veins', 'Varicose veins are swollen, twisted veins that you can see just under the surface of the skin, usually in the legs.', 'Weak or damaged valves in the veins, leading to blood pooling.', 'Compression stockings, lifestyle changes, procedures to remove or close veins.'),
('Hepatitis A', 'Hepatitis A is a highly contagious liver infection caused by the hepatitis A virus (HAV). It is usually transmitted through ingestion of contaminated food or water.', 'Hepatitis A virus (HAV) infection.', 'Supportive care, hydration, and rest. Vaccination for prevention.')
;